# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://quicktasks.ismael.casimpan.com/"  # Include trailing slash
title = "IT Quicktasks"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2018–2022, Ismael Casimpan Jr.; All Rights Reserved"
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
